import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nextjs Postman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="p-4">
          <div className="container mx-auto flex justify-center items-center">
            <h1 className="text-2xl">Nextjs Postman</h1>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
